.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH hipfire-host-profile 1  "hipfire-host-profile " 
.SH NAME
hipfire\-host\-profile \- Measure host, GPU\-copy, and model storage bandwidth
.SH SYNOPSIS
\fBhipfire\-host\-profile\fR [\fIARGS\fR] 
.SH DESCRIPTION
Measure host, GPU\-copy, and model storage bandwidth
.SH OPTIONS
.TP
[\fIARGS\fR]
Arguments forwarded to hipfire\-host\-profile
