.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH hipfire-repack 1  "hipfire-repack "
.SH NAME
hipfire\-repack \- Reshuffle a canonical .hfq into an arch\-optimal layout (<model>.<arch>.hfq)
.SH SYNOPSIS
\fBhipfire\-repack\fR [\fIARGS\fR]
.SH DESCRIPTION
Reshuffle a canonical .hfq into an arch\-optimal layout (<model>.<arch>.hfq)
.SH OPTIONS
.TP
[\fIARGS\fR]
Arguments forwarded to the oq4_repack runner
