import { describe, expect, test } from "bun:test";
import { buildBatchHealthPayload, buildPrefillBatchHealthPayload, type BatchExecutionMode } from "./prefill_batch_health";

describe("prefill batch health payload", () => {
  test("returns disabled payload when batching disabled", () => {
    expect(buildPrefillBatchHealthPayload({
      enabled: false,
      queued: 0,
      eligible: 0,
      selected: 0,
      skipped: 0,
      cacheHits: 0,
      cacheMisses: 0,
      queueSize: 0,
      generateBatchPrefillCapability: "unknown",
      generateBatchPrefillCapabilityReason: "not_probed",
      queueWaitReason: "disabled",
      fallbackReason: "batching_disabled",
      runtimeDispatchSkippedReason: "not_enabled",
      selectedBatchSize: 0,
    })).toEqual({
      enabled: false,
    });
  });

  test("includes serialized batching metadata when enabled", () => {
    expect(buildPrefillBatchHealthPayload({
      enabled: true,
      queued: 2,
      eligible: 1,
      selected: 0,
      skipped: 1,
      totalBatches: 6,
      fusedBatches: 4,
      fallbackBatches: 2,
      batchSizeHistogram: { "2": 3, "4": 1 },
      cacheHits: 3,
      cacheMisses: 4,
      metadataCacheHits: 5,
      runtimeCacheHits: 3,
      queueSize: 5,
      pendingRequests: 1,
      residentRuntimeSessions: 2,
      residentStateLimit: 8,
      spillableBatchMax: 16,
      spillableSessions: 3,
      stateCacheDisk: true,
      stateCacheDiskMinPriority: 128,
      diskSpillAllowed: true,
      stateCacheEvictionsTotal: 7,
      stateCacheRecomputeRequiredTotal: 2,
      generateBatchPrefillCapability: "unsupported",
      generateBatchPrefillCapabilityReason: "per_session_runtime_state_unavailable",
      queueWaitReason: "waiting",
      fallbackReason: "queue_wait:waiting",
      runtimeDispatchSkippedReason: "daemon_generate_batch_prefill_unsupported",
      selectedBatchSize: 4,
      lastPrefillTokens: 128,
      lastPrefillMs: 8,
      lastPrefillTokS: 16000,
      daemonPrefillPlan: "fused_dense_qwen35_candidate",
      daemonPrefillBackend: "serial_reference",
    })).toEqual({
      enabled: true,
      queued: 2,
      eligible: 1,
      selected: 0,
      skipped: 1,
      total_batches: 6,
      fused_batches: 4,
      fallback_batches: 2,
      batch_size_histogram: { "2": 3, "4": 1 },
      cache_hits: 3,
      cache_misses: 4,
      metadata_cache_hits: 5,
      runtime_cache_hits: 3,
      queue_size: 5,
      pending_requests: 1,
      resident_runtime_sessions: 2,
      resident_state_limit: 8,
      spillable_batch_max: 16,
      spillable_sessions: 3,
      state_cache_disk: true,
      state_cache_disk_min_priority: 128,
      disk_spill_allowed: true,
      state_cache_evictions_total: 7,
      state_cache_recompute_required_total: 2,
      generate_batch_prefill_capability: "unsupported",
      generate_batch_prefill_capability_reason: "per_session_runtime_state_unavailable",
      queue_wait_reason: "waiting",
      fallback_reason: "queue_wait:waiting",
      runtime_dispatch_skipped_reason: "daemon_generate_batch_prefill_unsupported",
      selected_batch_size: 4,
      last_prefill_tokens: 128,
      last_prefill_ms: 8,
      last_prefill_tok_s: 16000,
      daemon_prefill_plan: "fused_dense_qwen35_candidate",
      daemon_prefill_backend: "serial_reference",
    });
  });
});

describe("batch control-plane health payload", () => {
  test("includes machine-readable batch compatibility fields", () => {
    const mode: BatchExecutionMode = "serial_fallback";
    expect(buildBatchHealthPayload({
      enabled: true,
      queued: 1,
      selected: 0,
      total: 3,
      failed: 1,
      cancelled: 0,
      completed: 1,
      completion_window_supported: true,
      supported_endpoints: ["/v1/chat/completions", "/v1/responses"],
      execution_mode: mode,
      last_fallback_reason: "line_fallback:tools",
      batch_capability: "unsupported",
      batch_capability_reason: "per_session_runtime_state_unavailable",
      selected_batch_execution_mode: mode,
      fallback_reason: "line_fallback:tools",
      runtime_dispatch_skipped_reason: "daemon_generate_batch_prefill_unsupported",
      unsupported_mode_hits_total: 2,
      validation_errors_total: 1,
      streaming_rejections_total: 0,
    })).toEqual({
      enabled: true,
      queued: 1,
      selected: 0,
      total: 3,
      failed: 1,
      cancelled: 0,
      completed: 1,
      completion_window_supported: true,
      supported_endpoints: ["/v1/chat/completions", "/v1/responses"],
      execution_mode: mode,
      last_fallback_reason: "line_fallback:tools",
      batch_capability: "unsupported",
      batch_capability_reason: "per_session_runtime_state_unavailable",
      selected_batch_execution_mode: mode,
      fallback_reason: "line_fallback:tools",
      runtime_dispatch_skipped_reason: "daemon_generate_batch_prefill_unsupported",
      unsupported_mode_hits_total: 2,
      validation_errors_total: 1,
      streaming_rejections_total: 0,
    });
  });
});
